### ISSUE TITLE
Pre-release task list

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-boulder#2]
- [x] Check language flags
- [ ] Half of the "map" content area buttons are positioned behind the viewport:
  ![screen shot 2014-07-15 at 10 44 47](https://cloud.githubusercontent.com/assets/3191867/3581892/efad0cbc-0bf3-11e4-8a9c-3e4b1b3d72bf.png)
- [x] Front page cutom image area is missing
- [x] Make front page pixel perfect
- [x] Make common page pixel perfect
- [x]  Make blog listing page pixel perfect
- [x]  Make blog article page pixel perfect
- [x] Front page flexbox fallbacks
